In [2]:
import pandas as pd

# Load datasets
poems_df = pd.read_json("all_poems_database_cleaned.json")
poets_df = pd.read_json("poets_database.json")

# Display shapes
print(f"Poems Dataset Shape: {poems_df.shape}")
print(f"Poets Dataset Shape: {poets_df.shape}")

Poems Dataset Shape: (10146, 17)
Poets Dataset Shape: (1036, 4)

In [3]:
# Show structural info for poems
poems_df.info()

# Check missing values directly
poems_df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10146 entries, 0 to 10145
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   poem_id               10146 non-null  int64
 1   poet_id               10146 non-null  object
 2   era_id                10146 non-null  object
 3   title                 10146 non-null  object
 4   poet_name             10146 non-null  object
 5   full_poem_text        10146 non-null  object
 6   poetry_type           10146 non-null  object
 7   poem_sub_theme        10146 non-null  object
 8   number_of_verses      10146 non-null  int64
 9   era                   10146 non-null  object
 10  country               10146 non-null  object
 11  theme                 10146 non-null  object
 12  source_context        10146 non-null  object
 13  hijri_date            10146 non-null  object
 14  added_date_gregorian  10146 non-null  object
 15  added_time            10146 non-null  object
 16  source_url            10146 non-null  object
dtypes: int64(2), object(15)
memory usage: 1.3+ MB

poem_id                 0
poet_id                 0
era_id                  0
title                   0
poet_name               0
full_poem_text          0
poetry_type             0
poem_sub_theme          0
number_of_verses        0
era                     0
country                 0
theme                   0
source_context          0
hijri_date              0
added_date_gregorian    0
added_time              0
source_url              0
dtype: int64

In [4]:
# Preview first 5 rows with specific columns
poems_df[['poem_id', 'poet_name', 'title', 'era']].head()

,poem_id,poet_name,title,era
0,9918,الشيخ عبدالكريم بن مبارك آل زرع,نور العين مهدي خافق العلا,غير محدد
1,4507,الرباب بنت امريء القيس الكلبي,إن الذي كان نورا يستضاء به,القرن الأول الهجري
2,4508,الرباب بنت امريء القيس الكلبي,واحسينا فلا نسيت حسينا,القرن الأول الهجري
3,4509,جارية هاشمية تنعي الحسين,يا اهل يثرب لامقام لكم بها,القرن الأول الهجري
4,4504,عقبة بن عمرو السهمي,مررت على قبر الحسين بكربلا,القرن الأول الهجري

In [5]:
# Quick distribution of Eras
poems_df['era'].value_counts()

era
غير محدد                   8178
القرن الرابع عشر الهجري    1054
القرن الثالث عشر الهجري     153
القرن الأول الهجري          151
القرن الثاني عشر الهجري     135
القرن الثاني الهجري         115
القرن الرابع الهجري         102
القرن الثالث الهجري          49
القرن الثامن الهجري          45
القرن الحادي عشر الهجري      40
القرن العاشر الهجري          35
القرن السادس الهجري          30
القرن السابع الهجري          27
القرن الخامس الهجري          24
القرن التاسع الهجري           6
Not specified                 2
Name: count, dtype: int64

In [6]:
# Number of poems per poet (Showing top 20)
poems_per_poet = poems_df['poet_name'].value_counts()

print("--- Top 20 Poets by Poem Count ---")
poems_per_poet.head(20)

--- Top 20 Poets by Poem Count ---

poet_name
السيّد هاشم الموسوي                                                             562
في قصائد اللطم                                                                  149
مرتضى الشراري العاملي                                                           149
سنة 2016                                                                        127
رضا عبدالعزيز البحراني                                                          124
سنة 2017                                                                        116
حسين الثواب                                                                     111
ديوان القصائد الشعبية في مدح ورثاء العترة النبوية - عبد المهدي علوان التميمي     98
الفصل الثالث                                                                     94
عمار جبار خضير                                                                   92
عبدالرضا ميرزا الجدحفصي                                                          89
مكي كاظم العريبي                                                                 86
ديوان الشيخ محسن أبو الحب                                                        82
سنة 2013                                                                         81
السيد إسماعيل الحميري                                                            79
حسن آل حطيط العاملي                                                              77
سنة 2015                                                                         76
ديوان الحزن المعشوق - غازي الحداد البحراني                                       73
سنة 2014                                                                         73
ديوان أنوار الولاء - السيد هاشم الهاشمي                                          68
Name: count, dtype: int64

In [7]:
# Sub-themes distribution (e.g., أحزان, أفراح)
sub_theme_counts = poems_df['poem_sub_theme'].value_counts()

print("--- Poem Sub-Themes Distribution ---")
sub_theme_counts

--- Poem Sub-Themes Distribution ---

poem_sub_theme
عام        9570
أحزان       556
أفراح        18
General       2
Name: count, dtype: int64

In [8]:
# Main themes distribution
theme_counts = poems_df['theme'].value_counts()

print("--- Main Themes Distribution ---")
theme_counts

--- Main Themes Distribution ---

theme
غير محدد               9331
القصائد المشاركة        751
قصائد مجهولة المصدر      61
Not specified             2
القصائد الفائزة           1
Name: count, dtype: int64

In [9]:
# Cross-tabulation between Era and Sub-Theme
pd.crosstab(poems_df['era'], poems_df['poem_sub_theme'])

poem_sub_theme           General  أحزان  أفراح   عام
era
Not specified                  2      0      0     0
القرن الأول الهجري             0      0      0   151
القرن التاسع الهجري            0      0      0     6
القرن الثالث الهجري            0      0      0    49
القرن الثالث عشر الهجري        0      0      0   153
القرن الثامن الهجري            0      0      0    45
القرن الثاني الهجري            0      0      0   115
القرن الثاني عشر الهجري        0      0      0   135
القرن الحادي عشر الهجري        0      0      0    40
القرن الخامس الهجري            0      0      0    24
القرن الرابع الهجري            0      0      0   102
القرن الرابع عشر الهجري        0      0      0  1054
القرن السابع الهجري            0      0      0    27
القرن السادس الهجري            0      0      0    30
القرن العاشر الهجري            0      0      0    35
غير محدد                       0    556     18  7604

In [10]:
# Number of unique poets per era
poets_per_era = poems_df.groupby('era')['poet_name'].nunique().sort_values(ascending=False)

print("--- Number of Unique Poets per Era ---")
poets_per_era

--- Number of Unique Poets per Era ---

era
غير محدد                   668
القرن الرابع عشر الهجري    120
القرن الثالث عشر الهجري     50
القرن الأول الهجري          46
القرن الحادي عشر الهجري     23
القرن العاشر الهجري         22
القرن الرابع الهجري         16
القرن الثاني عشر الهجري     14
القرن السادس الهجري         10
القرن الثاني الهجري          9
القرن السابع الهجري          9
القرن الخامس الهجري          8
القرن الثالث الهجري          6
القرن الثامن الهجري          6
القرن التاسع الهجري          3
Not specified                2
Name: poet_name, dtype: int64

In [11]:
# Compare number of poems vs number of unique poets per era
era_stats = poems_df.groupby('era').agg(
    total_poems=('poem_id', 'count'),
    unique_poets=('poet_name', 'nunique')
).sort_values(by='total_poems', ascending=False)

era_stats

                         total_poems  unique_poets
era
غير محدد                        8178           668
القرن الرابع عشر الهجري         1054           120
القرن الثالث عشر الهجري          153            50
القرن الأول الهجري               151            46
القرن الثاني عشر الهجري          135            14
القرن الثاني الهجري              115             9
القرن الرابع الهجري              102            16
القرن الثالث الهجري               49             6
القرن الثامن الهجري               45             6
القرن الحادي عشر الهجري           40            23
القرن العاشر الهجري               35            22
القرن السادس الهجري               30            10
القرن السابع الهجري               27             9
القرن الخامس الهجري               24             8
القرن التاسع الهجري                6             3
Not specified                      2             2

In [12]:
# Print all unique country names in your dataset
print(poems_df['country'].unique())

['الجزيرة العربية  "السعودية"' 'غير محدد' 'سوريا' 'العراق' 'البحرين'
 'لبنان' 'مصر' 'السودان' 'عمان' 'اليمن' 'الأردن' 'الكويت' 'إيران'
 'أحمد شوقي - أمير الشعراء' 'فلسطين' 'الإمارات' 'المغرب']